version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Build release package
          command: ./gradlew assembleRelease
      - run:
          name: Deploy to Bintray
          command: ./gradlew bintrayUpload
    branches:
      only:
        - master