version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  deploy:
    steps:
      - checkout
      - run:
          name: Build release package
          command: ./gradlew assembleRelease
      - run:
          name: Deploy to Bintray
          command: ./gradlew bintrayUpload


workflows:
  version: 2
  test-n-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
